name: "Legacy unit tests build for Som"
description: "This action builds legacy Unit Tests for Som on Ubuntu Linux/Windows"
inputs:
   target:
     required: true
     description: "Target specifies whether the build is for Linux or Windows"
runs:
  using: "composite"
  steps:
    - name: Set permissions and prepare the library
      shell: bash
      run: |
        chmod +x .github/actions/legacy_unit_tests.sh
    - name: Build Som Unit Tests
      shell: bash
      run: |
        source .github/actions/legacy_unit_tests.sh
        build_som_unit_tests ${{ inputs.target }}
